### ISSUE TITLE
:question: Training without depth

### ISSUE THREAD

**Issue by DRM-Free** [wenbowen123/iros20-6d-pose-tracking#30] opened 2021-08-19 09:01 UTC
Hello, I am trying to reproduce your works on a custom dataset, however I do not have access to depth data. What would be some minimal modification to the code so as to reproduce the "No depth" situation from your ablation study ?

**Comment by wenbowen123** [comment] 2021-08-19 17:46
Possible duplicate of [this](https://github.com/wenbowen123/iros20-6d-pose-tracking/issues/18).

**Comment by DRM-Free** [comment] 2021-08-26 13:36
Yes, this is probably a duplicate, I will delete when I manage to reproduce the solution you mentioned. I need this to generate a lot of labeled real world photos to use as a validation dataset. I understood that the lack of depth data is expected to alter performances. Can you think of an alternative with reasonable tracking quality without depth data, in the case that se3-tracknet fails ?

**Closed as completed** 2021-09-09 12:57 UTC
